language: node_js
node_js: "12"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE testdb;'
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
